### PR TITLE
Create rockpaperscissor.py

### PR DESCRIPTION
**Pull request by dandre2**

### CODE REVIEW

**Review by rakirs2 — COMMENTED** [review]
Just something for you to see/how I can give different comments etc.. Try replying to this with anything.›

**Review by rakirs2 — CHANGES_REQUESTED** [review]
Let's try to get this as a completed solution before we add it as an example solution.

**Comment by dandre2** [comment]
import random
options=['Rock','Paper','Scissor']
name=input('type your name here')
ComputerScore=0
PlayerScore=0
NumberOfRounds=0
While=True
print(f"Welcome :{name.title()}")
while NumberOfRounds<5:
ComputerOption=random.choice(options)
PlayerOption=input("Enter Rock,Paper or Scissor :").title()
print(f"Computer option :{ComputerOption}")
print(f"{name.title()} option :{PlayerOption}")
NumberOfRounds += 1
if ComputerOption==PlayerOption:
print('Tie')
elif (ComputerOption=='Rock' and PlayerOption == 'Scissor') or (
ComputerOption=='Scissor' and PlayerOption=='Paper') or (ComputerOption==
'Paper' and ComputerOption=='Rock'):
print("Computer wins")
ComputerScore += 1
elif (PlayerOption=='Rock' and ComputerOption == 'Scissor') or (PlayerOption
=='Scissor' and ComputerOption=='Paper') or (PlayerOption=='Paper' and
ComputerOption=='Rock'):
print(f"{name.title()} wins")
PlayerScore += 1
else:
print("-------------------------")
print("")
print(f"Round No: {NumberOfRounds}")
print("------ Score Board ------")
print(f"{name.title()}: {PlayerScore} | Computer: {ComputerScore}")
print("===============================")
print("")
if NumberOfRounds==5:
While=True
break
if PlayerScore==ComputerScore:
print("Draw!!")
elif PlayerScore>ComputerScore:
print(f"Congrats {name.title()}, You won the game!!")
else:
print(f"Oops Computer won the game!! Better luck next time {name.title()}!")

**Comment by dandre2** [comment]
import random
while True:
    player1score=0
    player2score=0     
    player2 = None
    rpslist =  ["rock","paper","scissors"]
    print("Do you want to play a game of rock paper scissors yes or no")
    y=input()
    if y==('yes'):
        print('pick between rock,paper,or scissors')
    if y==('no'):
        break
    player1=input()

    if player1 in rpslist:
        player2 = random.choice(rpslist)
        print(player2)   

    if player2==player1:
        print('tie')
        print(player1score)
        print(player2score)
    if (player2=='Rock' and player1 == 'Scissor') or (
player2=='Scissor' and player1=='Paper') or (player2==
'Paper' and player1=='Rock'):
        print("Computer wins")
        player2score + 1
        print(player1score)
        print(player2score)
    if(player1=='Rock' and player2 == 'Scissor') or (player1
=='Scissor' and player2=='Paper') or (player1=='Paper' and
player2=='Rock'):
        print("player1 wins")
player1score + 1
print(player1score)
print(player2score)

**Comment by dandre2** [comment]
it will not show the score

**Pull request merged**
